import { Pokemon, Ingredients, MainSkill, SubSkill } from "../types";
export const defaultpokemon = [
  {
    personalId: 0,
    name: "フシギダネ",
    level: 1,
    berry: "ドリのみ",
    ingredients: ["あまいミツ", "あんみんトマト", "ほっこりポテト"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 1,
    name: "フシギソウ",
    level: 1,
    berry: "ドリのみ",
    ingredients: ["あまいミツ", "あんみんトマト", "ほっこりポテト"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 2,
    name: "フシギバナ",
    level: 1,
    berry: "ドリのみ",
    ingredients: ["あまいミツ", "あんみんトマト", "ほっこりポテト"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 3,
    name: "ヒトカゲ",
    level: 1,
    berry: "ヒメリのみ",
    ingredients: ["マメミート", "あったかジンジャー", "げきからハーブ"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 4,
    name: "リザード",
    level: 1,
    berry: "ヒメリのみ",
    ingredients: ["マメミート", "あったかジンジャー", "げきからハーブ"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 5,
    name: "リザードン",
    level: 1,
    berry: "ヒメリのみ",
    ingredients: ["マメミート", "あったかジンジャー", "げきからハーブ"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 6,
    name: "ゼニガメ",
    level: 1,
    berry: "オレンのみ",
    ingredients: ["モーモーミルク", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 7,
    name: "カメール",
    level: 1,
    berry: "オレンのみ",
    ingredients: ["モーモーミルク", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 8,
    name: "カメックス",
    level: 1,
    berry: "オレンのみ",
    ingredients: ["モーモーミルク", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 9,
    name: "キャタピー",
    level: 1,
    berry: "ラムのみ",
    ingredients: ["あまいミツ", "あんみんトマト", "ワカクサ大豆"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 10,
    name: "トランセル",
    level: 1,
    berry: "ラムのみ",
    ingredients: ["あまいミツ", "あんみんトマト", "ワカクサ大豆"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 11,
    name: "バタフリー",
    level: 1,
    berry: "ラムのみ",
    ingredients: ["あまいミツ", "あんみんトマト", "ワカクサ大豆"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 12,
    name: "コラッタ",
    level: 1,
    berry: "キーのみ",
    ingredients: ["とくせんリンゴ", "ワカクサ大豆", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 13,
    name: "ラッタ",
    level: 1,
    berry: "キーのみ",
    ingredients: ["とくせんリンゴ", "ワカクサ大豆", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 14,
    name: "アーボ",
    level: 1,
    berry: "カゴのみ",
    ingredients: ["マメミート", "とくせんエッグ", "げきからハーブ"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 15,
    name: "アーボック",
    level: 1,
    berry: "カゴのみ",
    ingredients: ["マメミート", "とくせんエッグ", "げきからハーブ"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 16,
    name: "ピカチュウ",
    level: 1,
    berry: "ウブのみ",
    ingredients: ["とくせんリンゴ", "あったかジンジャー", "とくせんエッグ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 17,
    name: "ピカチュウ(ハロウィン)",
    level: 1,
    berry: "ウブのみ",
    ingredients: ["とくせんリンゴ", "あったかジンジャー", "とくせんエッグ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 18,
    name: "ライチュウ",
    level: 1,
    berry: "ウブのみ",
    ingredients: ["とくせんリンゴ", "あったかジンジャー", "とくせんエッグ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 19,
    name: "ピッピ",
    level: 1,
    berry: "モモンのみ",
    ingredients: ["とくせんリンゴ", "あまいミツ", "ワカクサ大豆"],
    nature: "いじっぱり",
    mainSkill: "ゆびをふる",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 20,
    name: "ピクシー",
    level: 1,
    berry: "モモンのみ",
    ingredients: ["とくせんリンゴ", "あまいミツ", "ワカクサ大豆"],
    nature: "いじっぱり",
    mainSkill: "ゆびをふる",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 21,
    name: "プリン",
    level: 1,
    berry: "モモンのみ",
    ingredients: ["あまいミツ", "ピュアなオイル", "リラックスカカオ"],
    nature: "いじっぱり",
    mainSkill: "げんきオールS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 22,
    name: "プクリン",
    level: 1,
    berry: "モモンのみ",
    ingredients: ["あまいミツ", "ピュアなオイル", "リラックスカカオ"],
    nature: "いじっぱり",
    mainSkill: "げんきオールS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 23,
    name: "ディグダ",
    level: 1,
    berry: "フィラのみ",
    ingredients: ["あんみんトマト", "ふといながねぎ", "ワカクサ大豆"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 24,
    name: "ダグトリオ",
    level: 1,
    berry: "フィラのみ",
    ingredients: ["あんみんトマト", "ふといながねぎ", "ワカクサ大豆"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 25,
    name: "ニャース",
    level: 1,
    berry: "キーのみ",
    ingredients: ["モーモーミルク", "マメミート", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "ゆめのかけらゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 26,
    name: "ペルシアン",
    level: 1,
    berry: "キーのみ",
    ingredients: ["モーモーミルク", "マメミート", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "ゆめのかけらゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 27,
    name: "コダック",
    level: 1,
    berry: "オレンのみ",
    ingredients: ["リラックスカカオ", "とくせんリンゴ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 28,
    name: "ゴルダック",
    level: 1,
    berry: "オレンのみ",
    ingredients: ["リラックスカカオ", "とくせんリンゴ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 29,
    name: "マンキー",
    level: 1,
    berry: "クラボのみ",
    ingredients: ["マメミート", "あじわいキノコ", "あまいミツ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 30,
    name: "オコリザル",
    level: 1,
    berry: "クラボのみ",
    ingredients: ["マメミート", "あじわいキノコ", "あまいミツ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 31,
    name: "ガーディ",
    level: 1,
    berry: "ヒメリのみ",
    ingredients: ["げきからハーブ", "マメミート", "モーモーミルク"],
    nature: "いじっぱり",
    mainSkill: "おてつだいサポートS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 32,
    name: "ウインディ",
    level: 1,
    berry: "ヒメリのみ",
    ingredients: ["げきからハーブ", "マメミート", "モーモーミルク"],
    nature: "いじっぱり",
    mainSkill: "おてつだいサポートS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 33,
    name: "マダツボミ",
    level: 1,
    berry: "ドリのみ",
    ingredients: ["あんみんトマト", "ほっこりポテト", "ふといながねぎ"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 34,
    name: "ウツドン",
    level: 1,
    berry: "ドリのみ",
    ingredients: ["あんみんトマト", "ほっこりポテト", "ふといながねぎ"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 35,
    name: "ウツボット",
    level: 1,
    berry: "ドリのみ",
    ingredients: ["あんみんトマト", "ほっこりポテト", "ふといながねぎ"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 36,
    name: "イシツブテ",
    level: 1,
    berry: "オボンのみ",
    ingredients: ["ワカクサ大豆", "ほっこりポテト", "あじわいキノコ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 37,
    name: "ゴローン",
    level: 1,
    berry: "オボンのみ",
    ingredients: ["ワカクサ大豆", "ほっこりポテト", "あじわいキノコ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 38,
    name: "ゴローニャ",
    level: 1,
    berry: "オボンのみ",
    ingredients: ["ワカクサ大豆", "ほっこりポテト", "あじわいキノコ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 39,
    name: "ヤドン",
    level: 1,
    berry: "オレンのみ",
    ingredients: ["リラックスカカオ", "おいしいシッポ", "あんみんトマト"],
    nature: "いじっぱり",
    mainSkill: "げんきエールS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 40,
    name: "ヤドラン",
    level: 1,
    berry: "オレンのみ",
    ingredients: ["リラックスカカオ", "おいしいシッポ", "あんみんトマト"],
    nature: "いじっぱり",
    mainSkill: "げんきエールS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 41,
    name: "コイル",
    level: 1,
    berry: "ベリブのみ",
    ingredients: ["ピュアなオイル", "げきからハーブ", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "料理パワーアップS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 42,
    name: "レアコイル",
    level: 1,
    berry: "ベリブのみ",
    ingredients: ["ピュアなオイル", "げきからハーブ", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "料理パワーアップS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 43,
    name: "ドードー",
    level: 1,
    berry: "シーヤのみ",
    ingredients: ["ワカクサ大豆", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 44,
    name: "ドードリオ",
    level: 1,
    berry: "シーヤのみ",
    ingredients: ["ワカクサ大豆", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 45,
    name: "ゴース",
    level: 1,
    berry: "ブリーのみ",
    ingredients: ["げきからハーブ", "あじわいキノコ", "ピュアなオイル"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 46,
    name: "ゴースト",
    level: 1,
    berry: "ブリーのみ",
    ingredients: ["げきからハーブ", "あじわいキノコ", "ピュアなオイル"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 47,
    name: "ゲンガー",
    level: 1,
    berry: "ブリーのみ",
    ingredients: ["げきからハーブ", "あじわいキノコ", "ピュアなオイル"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 48,
    name: "イワーク",
    level: 1,
    berry: "オボンのみ",
    ingredients: ["あんみんトマト", "マメミート", "ほっこりポテト"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 49,
    name: "カラカラ",
    level: 1,
    berry: "フィラのみ",
    ingredients: ["あったかジンジャー", "リラックスカカオ", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 50,
    name: "ガラガラ",
    level: 1,
    berry: "フィラのみ",
    ingredients: ["あったかジンジャー", "リラックスカカオ", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 51,
    name: "ガルーラ",
    level: 1,
    berry: "キーのみ",
    ingredients: ["あったかジンジャー", "ほっこりポテト", "ワカクサ大豆"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 52,
    name: "バリヤード",
    level: 1,
    berry: "マゴのみ",
    ingredients: ["あんみんトマト", "ほっこりポテト", "ふといながねぎ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 53,
    name: "カイロス",
    level: 1,
    berry: "ラムのみ",
    ingredients: ["あまいミツ", "とくせんリンゴ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 54,
    name: "メタモン",
    level: 1,
    berry: "キーのみ",
    ingredients: ["ピュアなオイル", "ふといながねぎ", "おいしいシッポ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 55,
    name: "イーブイ",
    level: 1,
    berry: "キーのみ",
    ingredients: ["モーモーミルク", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 56,
    name: "シャワーズ",
    level: 1,
    berry: "オレンのみ",
    ingredients: ["モーモーミルク", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 57,
    name: "サンダース",
    level: 1,
    berry: "ウブのみ",
    ingredients: ["モーモーミルク", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "おてつだいサポートS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 58,
    name: "ブースター",
    level: 1,
    berry: "ヒメリのみ",
    ingredients: ["モーモーミルク", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "料理パワーアップS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 59,
    name: "チコリータ",
    level: 1,
    berry: "ドリのみ",
    ingredients: ["リラックスカカオ", "あまいミツ", "ふといながねぎ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 60,
    name: "ベイリーフ",
    level: 1,
    berry: "ドリのみ",
    ingredients: ["リラックスカカオ", "あまいミツ", "ふといながねぎ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 61,
    name: "メガニウム",
    level: 1,
    berry: "ドリのみ",
    ingredients: ["リラックスカカオ", "あまいミツ", "ふといながねぎ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 62,
    name: "ヒノアラシ",
    level: 1,
    berry: "ヒメリのみ",
    ingredients: ["あったかジンジャー", "げきからハーブ", "ピュアなオイル"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 63,
    name: "マグマラシ",
    level: 1,
    berry: "ヒメリのみ",
    ingredients: ["あったかジンジャー", "げきからハーブ", "ピュアなオイル"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 64,
    name: "バクフーン",
    level: 1,
    berry: "ヒメリのみ",
    ingredients: ["あったかジンジャー", "げきからハーブ", "ピュアなオイル"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 65,
    name: "ワニノコ",
    level: 1,
    berry: "オレンのみ",
    ingredients: ["マメミート", "ピュアなオイル", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 66,
    name: "アリゲイツ",
    level: 1,
    berry: "オレンのみ",
    ingredients: ["マメミート", "ピュアなオイル", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 67,
    name: "オーダイル",
    level: 1,
    berry: "オレンのみ",
    ingredients: ["マメミート", "ピュアなオイル", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 68,
    name: "ピチュー",
    level: 1,
    berry: "ウブのみ",
    ingredients: ["とくせんリンゴ", "あったかジンジャー", "とくせんエッグ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 69,
    name: "ピィ",
    level: 1,
    berry: "モモンのみ",
    ingredients: ["とくせんリンゴ", "あまいミツ", "ワカクサ大豆"],
    nature: "いじっぱり",
    mainSkill: "ゆびをふる",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 70,
    name: "ププリン",
    level: 1,
    berry: "モモンのみ",
    ingredients: ["あまいミツ", "ピュアなオイル", "リラックスカカオ"],
    nature: "いじっぱり",
    mainSkill: "げんきオールS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 71,
    name: "トゲピー",
    level: 1,
    berry: "モモンのみ",
    ingredients: ["とくせんエッグ", "あったかジンジャー", "リラックスカカオ"],
    nature: "いじっぱり",
    mainSkill: "ゆびをふる",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 72,
    name: "トゲチック",
    level: 1,
    berry: "モモンのみ",
    ingredients: ["とくせんエッグ", "あったかジンジャー", "リラックスカカオ"],
    nature: "いじっぱり",
    mainSkill: "ゆびをふる",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 73,
    name: "メリープ",
    level: 1,
    berry: "ウブのみ",
    ingredients: ["げきからハーブ", "とくせんエッグ", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージM",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 74,
    name: "モココ",
    level: 1,
    berry: "ウブのみ",
    ingredients: ["げきからハーブ", "とくせんエッグ", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージM",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 75,
    name: "デンリュウ",
    level: 1,
    berry: "ウブのみ",
    ingredients: ["げきからハーブ", "とくせんエッグ", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージM",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 76,
    name: "ウソッキー",
    level: 1,
    berry: "オボンのみ",
    ingredients: ["あんみんトマト", "ワカクサ大豆", "あじわいキノコ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージM",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 77,
    name: "エーフィ",
    level: 1,
    berry: "マゴのみ",
    ingredients: ["モーモーミルク", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージM",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 78,
    name: "ブラッキー",
    level: 1,
    berry: "ウイのみ",
    ingredients: ["モーモーミルク", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 79,
    name: "ヤドキング",
    level: 1,
    berry: "オレンのみ",
    ingredients: ["リラックスカカオ", "おいしいシッポ", "あんみんトマト"],
    nature: "いじっぱり",
    mainSkill: "げんきエールS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 80,
    name: "ソーナンス",
    level: 1,
    berry: "マゴのみ",
    ingredients: ["とくせんリンゴ", "あじわいキノコ", "ピュアなオイル"],
    nature: "いじっぱり",
    mainSkill: "げんきエールS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 81,
    name: "ハガネール",
    level: 1,
    berry: "ベリブのみ",
    ingredients: ["あんみんトマト", "マメミート", "ほっこりポテト"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 82,
    name: "ヘラクロス",
    level: 1,
    berry: "ラムのみ",
    ingredients: ["あまいミツ", "あじわいキノコ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 83,
    name: "デルビル",
    level: 1,
    berry: "ウイのみ",
    ingredients: ["げきからハーブ", "あったかジンジャー", "ふといながねぎ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 84,
    name: "ヘルガー",
    level: 1,
    berry: "ウイのみ",
    ingredients: ["げきからハーブ", "あったかジンジャー", "ふといながねぎ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 85,
    name: "ヨーギラス",
    level: 1,
    berry: "オボンのみ",
    ingredients: ["あったかジンジャー", "ワカクサ大豆", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 86,
    name: "サナギラス",
    level: 1,
    berry: "オボンのみ",
    ingredients: ["あったかジンジャー", "ワカクサ大豆", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 87,
    name: "バンギラス",
    level: 1,
    berry: "ウイのみ",
    ingredients: ["あったかジンジャー", "ワカクサ大豆", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 88,
    name: "ナマケロ",
    level: 1,
    berry: "キーのみ",
    ingredients: ["あんみんトマト", "あまいミツ", "とくせんリンゴ"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 89,
    name: "ヤルキモノ",
    level: 1,
    berry: "キーのみ",
    ingredients: ["あんみんトマト", "あまいミツ", "とくせんリンゴ"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 90,
    name: "ケッキング",
    level: 1,
    berry: "キーのみ",
    ingredients: ["あんみんトマト", "あまいミツ", "とくせんリンゴ"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 91,
    name: "ヤミラミ",
    level: 1,
    berry: "ウイのみ",
    ingredients: ["ピュアなオイル", "あじわいキノコ", "リラックスカカオ"],
    nature: "いじっぱり",
    mainSkill: "ゆめのかけらゲットS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 92,
    name: "ゴクリン",
    level: 1,
    berry: "カゴのみ",
    ingredients: ["ワカクサ大豆", "あじわいキノコ", "あまいミツ"],
    nature: "いじっぱり",
    mainSkill: "ゆめのかけらゲットS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 93,
    name: "マルノーム",
    level: 1,
    berry: "カゴのみ",
    ingredients: ["ワカクサ大豆", "あじわいキノコ", "あまいミツ"],
    nature: "いじっぱり",
    mainSkill: "ゆめのかけらゲットS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 94,
    name: "チルット",
    level: 1,
    berry: "シーヤのみ",
    ingredients: ["とくせんエッグ", "ワカクサ大豆", "とくせんリンゴ"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 95,
    name: "チルタリス",
    level: 1,
    berry: "ヤチェのみ",
    ingredients: ["とくせんエッグ", "ワカクサ大豆", "とくせんリンゴ"],
    nature: "いじっぱり",
    mainSkill: "げんきチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 96,
    name: "カゲボウズ",
    level: 1,
    berry: "ブリーのみ",
    ingredients: ["ピュアなオイル", "あったかジンジャー", "あじわいキノコ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 97,
    name: "カゲボウズ",
    level: 1,
    berry: "ブリーのみ",
    ingredients: ["ピュアなオイル", "あったかジンジャー", "あじわいキノコ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS(ランダム)",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 98,
    name: "アブソル",
    level: 1,
    berry: "ウイのみ",
    ingredients: ["リラックスカカオ", "とくせんリンゴ", "あじわいキノコ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 99,
    name: "ソーナノ",
    level: 1,
    berry: "マゴのみ",
    ingredients: ["とくせんリンゴ", "あじわいキノコ", "ピュアなオイル"],
    nature: "いじっぱり",
    mainSkill: "げんきエールS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 100,
    name: "タマザラシ",
    level: 1,
    berry: "チーゴのみ",
    ingredients: ["ピュアなオイル", "マメミート", "あったかジンジャー"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 101,
    name: "トドグラー",
    level: 1,
    berry: "チーゴのみ",
    ingredients: ["ピュアなオイル", "マメミート", "あったかジンジャー"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 102,
    name: "トドゼルガ",
    level: 1,
    berry: "チーゴのみ",
    ingredients: ["ピュアなオイル", "マメミート", "あったかジンジャー"],
    nature: "いじっぱり",
    mainSkill: "食材ゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 103,
    name: "ウソハチ",
    level: 1,
    berry: "オボンのみ",
    ingredients: ["あんみんトマト", "ワカクサ大豆", "あじわいキノコ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージM",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 104,
    name: "マネネ",
    level: 1,
    berry: "マゴのみ",
    ingredients: ["あんみんトマト", "ほっこりポテト", "ふといながねぎ"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 105,
    name: "リオル",
    level: 1,
    berry: "クラボのみ",
    ingredients: ["ピュアなオイル", "ほっこりポテト", "とくせんエッグ"],
    nature: "いじっぱり",
    mainSkill: "ゆめのかけらゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 106,
    name: "ルカリオ",
    level: 1,
    berry: "クラボのみ",
    ingredients: ["ピュアなオイル", "ほっこりポテト", "とくせんエッグ"],
    nature: "いじっぱり",
    mainSkill: "ゆめのかけらゲットS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 107,
    name: "グレッグル",
    level: 1,
    berry: "カゴのみ",
    ingredients: ["ピュアなオイル", "マメミート", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 108,
    name: "ドクロッグ",
    level: 1,
    berry: "カゴのみ",
    ingredients: ["ピュアなオイル", "マメミート", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "エナジーチャージS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 109,
    name: "ジバコイル",
    level: 1,
    berry: "ベリブのみ",
    ingredients: ["ピュアなオイル", "げきからハーブ", "spacer.gif"],
    nature: "いじっぱり",
    mainSkill: "料理パワーアップS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 110,
    name: "トゲキッス",
    level: 1,
    berry: "モモンのみ",
    ingredients: ["とくせんエッグ", "あったかジンジャー", "リラックスカカオ"],
    nature: "いじっぱり",
    mainSkill: "ゆびをふる",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 111,
    name: "リーフィア",
    level: 1,
    berry: "ドリのみ",
    ingredients: ["モーモーミルク", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "げんきエールS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 112,
    name: "グレイシア",
    level: 1,
    berry: "チーゴのみ",
    ingredients: ["モーモーミルク", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "料理パワーアップS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },

  {
    personalId: 113,
    name: "ニンフィア",
    level: 1,
    berry: "モモンのみ",
    ingredients: ["モーモーミルク", "リラックスカカオ", "マメミート"],
    nature: "いじっぱり",
    mainSkill: "げんきオールS",
    subSkill: ["スキル確率アップM", "スキル確率アップS", "睡眠EXPボーナス"],
  },
] as Pokemon[];
